- name: variables with play
  hosts: localhost
  vars:
    course: DevOps
    trainer: Siva Kumar
    duration: 110HRS
  tasks:
    - name: checking variables
      vars: 
        course: "DevOps with AWS"
      ansible.builtin.debug:
        msg: Hi, I am learning {{course}}, Trainer is {{trainer}}, Duration is
          {{duration}}
