- name: variables with preference
  hosts: localhost
  vars_files:
  - variaables.yaml
  vars_prompt:
  - name: person
    prompt: Please enter your name
    private: false
  - name: wishes
    prompt: please enter your wishes
    private: false
  vars:
    person: "Prudhvi from play"
    wishes: "Morning from play"
  tasks:
  - name: checking variables
    vars:
      person: "Prudhvi from task"
      wishes: "Morning from task"
    ansible.builtin.debug:
     msg: "Hi, {{person}} Good {{wishes}}"