- name: Installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing
    ansible.builtin.package:
      name: {{item}}
      state: present
    loop:
    - git
    - nginx
    - mysql
    - postfix  